server:
  port: 5555
  netty:
    idle-timeout: 10m

eureka:
  instance:
    preferIpAddress: true
    metadataMap:
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}
  client:
    enabled: false
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: gateway-server
  cloud:
    config:
      enabled: false
    gateway:
      # seems spring cloud gateway does not support a global context path like /api
      defaultFilters:
        - StripPrefix=2
      routes:
        - id: baidu
          uri: http://baidu.com
          predicates:
            - Method=GET
        - id: authentication-id
          uri: http://localhost:8901
          predicates:
            - Path=/api/auth/**
        - id: organization-id
          uri: http://localhost:8085
          predicates:
            - Path=/api/organization/**
        - id: license-id
          uri: http://localhost:8080
          predicates:
            - Path=/api/license/**
  #config:
  #  import: optional:configserver:http://dummy-configserver/
  security:
    user:
      name: actuator
      password: actuator
      roles: ACTUATOR
  sleuth:
    #reactor:
    #  instrumentation-type: decorate_on_each
    reactor:
      instrumentation-type: decorate_on_each
    sampler:
      probability: 0.0
  zipkin:
    sender:
      # otherwise rabbit is used if available
      type: WEB

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.gonwan.springcloud: DEBUG
