armeria:
  ports:
  - port: 9411

# https://stackoverflow.com/questions/39174579/how-to-configure-spring-cloud-zipkin-server-with-mysql-for-persistence
zipkin:
  storage:
    type: mysql

encrypt:
  key: IMSYMMETRIC

spring:
  application:
    name: zipkin-server
  cloud:
    config:
      enabled: true
      # allow command line override
      allowOverride: true
      overrideSystemProperties: false
  datasource:
    url: "jdbc:mysql://10.228.131.133:3306/sc_database?useUnicode=true&characterEncoding=utf8"
    jdbcUrl: ${spring.datasource.url}
    username: "springcloud"
    password: "{cipher}38b6dd6855bccf5682b4ca4762b278ce66421167be9d5ec4c919e4fb8e236cd4"
    driverClassName: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimumIdle: 1
      maximumPoolSize: 2
      idleTimeout: 600000
      maxLifetime: 1800000
  sql:
    init:
      mode: ALWAYS
      schema-locations: classpath:mysql.sql

management:
  metrics:
    web:
      server:
        request:
          autotime:
            enabled: false

logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.gonwan.springcloud: DEBUG
