version: '2'

services:
  # zipkin docker images require manually create mysql schemes, just use the java version here.
  zipkin:
    image: gonwan/sc-zipkin-server:${BUILD_NAME}
    ports:
    - "9411:9411"
    environment:
      PROFILE: "cdh"
      SERVER_PORT: "9411"
      CONFIG_SERVER_URI: "http://config-server:8888/"
      CONFIG_SERVER_PORT: "8888"
  eureka-server:
    image: gonwan/sc-eureka-server:${BUILD_NAME}
    ports:
    - "8761:8761"
    environment:
      SERVER_PORT: "8761"
  config-server:
    image: gonwan/sc-config-server:${BUILD_NAME}
    ports:
    - "8888:8888"
    environment:
      SERVER_PORT: "8888"
      EUREKA_SERVER_URI: "http://eureka-server:8761/eureka/"
      EUREKA_SERVER_PORT: "8761"
  gateway-server:
    image: gonwan/sc-gateway-server:${BUILD_NAME}
    ports:
    - "5555:5555"
    environment:
      PROFILE: "cdh"
      SERVER_PORT: "5555"
      EUREKA_SERVER_URI: "http://eureka-server:8761/eureka/"
      CONFIG_SERVER_URI: "http://config-server:8888/"
      ZIPKIN_URI: "http://zipkin:9411"
      EUREKA_SERVER_PORT: "8761"
      CONFIG_SERVER_PORT: "8888"
      ZIPKIN_PORT: "9411"
  authentication-service:
    image: gonwan/sc-authentication-service:${BUILD_NAME}
    ports:
    - "8901:8901"
    environment:
      PROFILE: "cdh"
      SERVER_PORT: "8901"
      EUREKA_SERVER_URI: "http://eureka-server:8761/eureka/"
      CONFIG_SERVER_URI: "http://config-server:8888/"
      EUREKA_SERVER_PORT: "8761"
      CONFIG_SERVER_PORT: "8888"
  organization-service:
    image: gonwan/sc-organization-service:${BUILD_NAME}
    ports:
    - "8085:8085"
    environment:
      PROFILE: "cdh"
      SERVER_PORT: "8085"
      EUREKA_SERVER_URI: "http://eureka-server:8761/eureka/"
      CONFIG_SERVER_URI: "http://config-server:8888/"
      ZIPKIN_URI: "http://zipkin:9411"
      AUTH_SERVICE_URI: "http://authentication-service:8901/user"
      EUREKA_SERVER_PORT: "8761"
      CONFIG_SERVER_PORT: "8888"
      ZIPKIN_PORT: "9411"
  license-service:
    image: gonwan/sc-license-service:${BUILD_NAME}
    ports:
    - "8080:8080"
    environment:
      PROFILE: "cdh"
      SERVER_PORT: "8080"
      EUREKA_SERVER_URI: "http://eureka-server:8761/eureka/"
      CONFIG_SERVER_URI: "http://config-server:8888/"
      ZIPKIN_URI: "http://zipkin:9411"
      AUTH_SERVICE_URI: "http://authentication-service:8901/user"
      EUREKA_SERVER_PORT: "8761"
      CONFIG_SERVER_PORT: "8888"
      ZIPKIN_PORT: "9411"
