server:
  port: 8901

eureka:
  instance:
    preferIpAddress: true
    metadataMap:
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}
  client:
    enabled: false
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: authentication-service
  config:
    import: optional:configserver:http://dummy-configserver/
  redis:
    host: 192.168.11.234
    port: 6379
  security:
    user:
      name: actuator
      password: actuator
      roles: ACTUATOR

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    #org.springframework.security: DEBUG
    com.gonwan.springcloud: DEBUG
