armeria:
  ports:
  - port: 9411

# https://stackoverflow.com/questions/39174579/how-to-configure-spring-cloud-zipkin-server-with-mysql-for-persistence
zipkin:
  storage:
    type: mysql

spring:
  application:
    name: zipkin-server
  cloud:
    config:
      enabled: false
  #config:
  #  import: optional:configserver:http://dummy-configserver/
  datasource:
    url: "jdbc:mysql://192.168.11.234:3306/sc_database?useUnicode=true&characterEncoding=utf8"
    jdbcUrl: ${spring.datasource.url}
    username: "springcloud"
    password: "sc_passw0rd"
    driverClassName: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimumIdle: 1
      maximumPoolSize: 2
      idleTimeout: 600000
      maxLifetime: 1800000
  sql:
    init:
      mode: ALWAYS
      schema-locations: classpath:mysql.sql

management:
  metrics:
    web:
      server:
        request:
          autotime:
            enabled: false

logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.gonwan.springcloud: DEBUG
