server:
  port: 8901

eureka:
  instance:
    preferIpAddress: true
    metadataMap:
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: authentication-service-legacy
  cloud:
    config:
      enabled: true
      # allow command line override
      allowOverride: true
      overrideSystemProperties: false
  redis:
    host: 10.228.131.133
    port: 6379
  security:
    user:
      name: actuator
      password: actuator
      roles: ACTUATOR

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.gonwan.springcloud: DEBUG
