server:
  port: 8085

eureka:
  instance:
    preferIpAddress: true
    metadataMap:
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

encrypt:
  key: IMSYMMETRIC

spring:
  application:
    name: organization-service
  cloud:
    config:
      enabled: true
      # allow command line override
      allowOverride: true
      overrideSystemProperties: false
    stream:
      bindings:
        output:
          destination: sc.organization.change.topic
          contentType: application/json
  datasource:
    url: "jdbc:mysql://10.228.131.133:3306/sc_database?useUnicode=true&characterEncoding=utf8"
    username: "springcloud"
    password: "{cipher}38b6dd6855bccf5682b4ca4762b278ce66421167be9d5ec4c919e4fb8e236cd4"
    driverClassName: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimumIdle: 1
      maximumPoolSize: 2
      idleTimeout: 600000
      maxLifetime: 1800000
  sql:
    init:
      mode: ALWAYS
      schema-locations: classpath:schema.sql
  rabbitmq:
    # vmware
    host: 192.168.127.129
    port: 5672
  security:
    user:
      name: actuator
      password: actuator
      roles: ACTUATOR
    oauth2:
      client:
        provider:
          sc-provider:
            # align with the attribute name in authentication service
            userNameAttribute: username
            userInfoUri: http://localhost:8901/user
        registration:
          sc-client1:
            provider: sc-provider
            clientId: eagleeye
            clientSecret: thisissecret
            authorizationGrantType: client_credentials,password,refresh_token
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    sender:
      # otherwise rabbit is used if available
      type: WEB

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true
        descriptions: false
    distribution:
      percentiles-histogram:
        http.server.requests: true
      slo:
        http.server.requests: 10ms, 20ms, 100ms, 1000ms

logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.gonwan.springcloud: DEBUG
