# 1. Install a local docker registry on CentOS7:
# # yum install docker-distribution
# # system start docker-distribution
#
# 2. On all docker clients, add following config to /etc/docker/daemon.json and restart docker:
# { "insecure-registries": ["192.168.11.235:5000"] }
# # systemctl restart docker
#
# 3. Push local docker images to the docker registry:
# # docker image tag gonwan/sc-eureka-server:2.0.0 192.168.11.235:5000/gonwan/sc-eureka-server:2.0.0
# # docker push 192.168.11.235:5000/gonwan/sc-eureka-server:2.0.0
# # docker image tag gonwan/sc-config-server:2.0.0 192.168.11.235:5000/gonwan/sc-config-server:2.0.0
# # docker push 192.168.11.235:5000/gonwan/sc-config-server:2.0.0
# # docker image tag gonwan/sc-zipkin-server:2.0.0 192.168.11.235:5000/gonwan/sc-zipkin-server:2.0.0
# # docker push 192.168.11.235:5000/gonwan/sc-zipkin-server:2.0.0
# # docker image tag gonwan/sc-gateway-server:2.0.0 192.168.11.235:5000/gonwan/sc-gateway-server:2.0.0
# # docker push 192.168.11.235:5000/gonwan/sc-gateway-server:2.0.0
# # docker image tag gonwan/sc-authentication-service:2.0.0 192.168.11.235:5000/gonwan/sc-authentication-service:2.0.0
# # docker push 192.168.11.235:5000/gonwan/sc-authentication-service:2.0.0
# # docker image tag gonwan/sc-organization-service:2.0.0 192.168.11.235:5000/gonwan/sc-organization-service:2.0.0
# # docker push 192.168.11.235:5000/gonwan/sc-organization-service:2.0.0
# # docker image tag gonwan/sc-license-service:2.0.0 192.168.11.235:5000/gonwan/sc-license-service:2.0.0
# # docker push 192.168.11.235:5000/gonwan/sc-license-service:2.0.0
#
# 4. To enable image deployment also enabled on a kubernetes master:
# # kubectl taint nodes cdh-node1 node-role.kubernetes.io/master:NoSchedule-
#
# 5. To boot into CentOS7 CUI/GUI mode:
# # systemctl set-default multi-user.target
# # systemctl set-default graphical.target
#

# eureka-server
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-server
spec:
  selector:
    app: eureka-server
  type: NodePort
  ports:
  - port: 8761
    nodePort: 31001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
      - name: eureka-server
        image: 192.168.11.235:5000/gonwan/sc-eureka-server:2.0.0
        ports:
        - containerPort: 8761
        env:
        - name: SERVER_PORT
          value: "8761"

# config-server
---
apiVersion: v1
kind: Service
metadata:
  name: config-server
spec:
  selector:
    app: config-server
  type: NodePort
  ports:
  - port: 8888
    nodePort: 31002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
      - name: config-server
        image: 192.168.11.235:5000/gonwan/sc-config-server:2.0.0
        ports:
        - containerPort: 8888
        env:
        - name: SERVER_PORT
          value: "8888"
        - name: EUREKA_SERVER_URI
          value: "http://eureka-server:8761/eureka/"
        - name: EUREKA_SERVER_PORT
          value: "8761"

# zipkin-server
---
apiVersion: v1
kind: Service
metadata:
  name: zipkin
spec:
  selector:
    app: zipkin-server
  type: NodePort
  ports:
  - port: 9411
    nodePort: 31003
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zipkin-server
  template:
    metadata:
      labels:
        app: zipkin-server
    spec:
      containers:
      - name: zipkin-server
        image: 192.168.11.235:5000/gonwan/sc-zipkin-server:2.0.0
        ports:
        - containerPort: 9411
        env:
        - name: PROFILE
          value: "default"
        - name: SERVER_PORT
          value: "9411"
        - name: CONFIG_SERVER_URI
          value: "http://config-server:8888/"
        - name: CONFIG_SERVER_PORT
          value: "8888"

# gateway-server
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-server
spec:
  selector:
    app: gateway-server
  type: NodePort
  ports:
  - port: 5555
    nodePort: 31004
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-server
  template:
    metadata:
      labels:
        app: gateway-server
    spec:
      containers:
      - name: gateway-server
        image: 192.168.11.235:5000/gonwan/sc-gateway-server:2.0.0
        ports:
        - containerPort: 5555
        env:
        - name: PROFILE
          value: "default"
        - name: SERVER_PORT
          value: "5555"
        - name: EUREKA_SERVER_URI
          value: "http://eureka-server:8761/eureka/"
        - name: CONFIG_SERVER_URI
          value: "http://config-server:8888/"
        - name: ZIPKIN_URI
          value: "http://zipkin:9411"
        - name: EUREKA_SERVER_PORT
          value: "8761"
        - name: CONFIG_SERVER_PORT
          value: "8888"
        - name: ZIPKIN_PORT
          value: "9411"

# authentication-service
---
apiVersion: v1
kind: Service
metadata:
  name: authentication-service
spec:
  selector:
    app: authentication-service
  type: NodePort
  ports:
  - port: 8901
    nodePort: 31005
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication-service
  template:
    metadata:
      labels:
        app: authentication-service
    spec:
      containers:
      - name: authentication-service
        image: 192.168.11.235:5000/gonwan/sc-authentication-service:2.0.0
        ports:
        - containerPort: 8901
        env:
        - name: PROFILE
          value: "default"
        - name: SERVER_PORT
          value: "8901"
        - name: EUREKA_SERVER_URI
          value: "http://eureka-server:8761/eureka/"
        - name: CONFIG_SERVER_URI
          value: "http://config-server:8888/"
        - name: EUREKA_SERVER_PORT
          value: "8761"
        - name: CONFIG_SERVER_PORT
          value: "8888"

# organization-service
---
apiVersion: v1
kind: Service
metadata:
  name: organization-service
spec:
  selector:
    app: organization-service
  type: NodePort
  ports:
  - port: 8085
    nodePort: 31006
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: organization-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: organization-service
  template:
    metadata:
      labels:
        app: organization-service
    spec:
      containers:
      - name: organization-service
        image: 192.168.11.235:5000/gonwan/sc-organization-service:2.0.0
        ports:
        - containerPort: 8085
        env:
        - name: PROFILE
          value: "default"
        - name: SERVER_PORT
          value: "8085"
        - name: EUREKA_SERVER_URI
          value: "http://eureka-server:8761/eureka/"
        - name: CONFIG_SERVER_URI
          value: "http://config-server:8888/"
        - name: ZIPKIN_URI
          value: "http://zipkin:9411"
        - name: AUTH_SERVICE_URI
          value: "http://authentication-service:8901/user"
        - name: EUREKA_SERVER_PORT
          value: "8761"
        - name: CONFIG_SERVER_PORT
          value: "8888"
        - name: ZIPKIN_PORT
          value: "9411"

# license-service
---
apiVersion: v1
kind: Service
metadata:
  name: license-service
spec:
  selector:
    app: license-service
  type: NodePort
  ports:
  - port: 8080
    nodePort: 31007
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: license-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: license-service
  template:
    metadata:
      labels:
        app: license-service
    spec:
      containers:
      - name: license-service
        image: 192.168.11.235:5000/gonwan/sc-license-service:2.0.0
        ports:
        - containerPort: 8080
        env:
        - name: PROFILE
          value: "default"
        - name: SERVER_PORT
          value: "8080"
        - name: EUREKA_SERVER_URI
          value: "http://eureka-server:8761/eureka/"
        - name: CONFIG_SERVER_URI
          value: "http://config-server:8888/"
        - name: ZIPKIN_URI
          value: "http://zipkin:9411"
        - name: AUTH_SERVICE_URI
          value: "http://authentication-service:8901/user"
        - name: EUREKA_SERVER_PORT
          value: "8761"
        - name: CONFIG_SERVER_PORT
          value: "8888"
        - name: ZIPKIN_PORT
          value: "9411"
