server:
  port: 8888

eureka:
  instance:
    preferIpAddress: true
  client:
    enabled: false
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# curl http://localhost:8888/encrypt -X POST -d 'sc_passw0rd'
#   38b6dd6855bccf5682b4ca4762b278ce66421167be9d5ec4c919e4fb8e236cd4
# curl http://localhost:8888/decrypt -X POST -d '38b6dd6855bccf5682b4ca4762b278ce66421167be9d5ec4c919e4fb8e236cd4'
#   sc_passw0rd
encrypt:
  key: IMSYMMETRIC

#spring:
#  cloud:
#    config:
#      #discovery:
#        # Client config for config server discovery:
#        # See: https://cloud.spring.io/spring-cloud-config/multi/multi__spring_cloud_config_client.html#discovery-first-bootstrap
#        #enabled: true
#        #service-id: config-server
#      server:
#        encrypt:
#          enabled: false
#        git:
#          uri: https://github.com/gonwan/spring-cloud-demo/
#          defaultLabel: master  # branch
#          searchPaths: |
#            config/zipkin-server,
#            config/gateway-server,
#            config/authentication-service,
#            config/license-service,
#            config/organization-service
#          #username: gonwan
#          #password: 123456

spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        encrypt:
          enabled: false
        native:
          searchLocations: |
            classpath:config/zipkin-server,
            classpath:config/gateway-server,
            classpath:config/authentication-service,
            classpath:config/license-service,
            classpath:config/organization-service
#            # An extra `/` required under windows when using absolute paths
#            file://${user.home}/Documents/github/restful/springcloud/config/zipkin-server,
#            file://${user.home}/Documents/github/restful/springcloud/config/gateway-server,
#            file://${user.home}/Documents/github/restful/springcloud/config/authentication-service,
#            file://${user.home}/Documents/github/restful/springcloud/config/license-service,
#            file://${user.home}/Documents/github/restful/springcloud/config/organization-service

logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.gonwan.springcloud: DEBUG
